#! /bin/bash

# Attaches an EBS volume (creating if necessary), attaches
# formats and mounts it to $MONGO_DIR

mount --rbind /host/dev /dev

if [[ "$DISABLE_THP" == "true" ]]; then
  echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
  echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
fi

VOLUME_NAME=${EBS_VOLUME_NAME}

VOLUME_SUFFIX=$(echo "$EBS_VOLUME_SIZE" | tail -c 2)

if [[ "$VOLUME_SUFFIX" != "G" ]]; then
  echo "Volume sizes must be specified in gigabytes (e.g. 100G)"
  exit 1
fi

VOLUME_SIZE=${EBS_VOLUME_SIZE%?}
VOLUME_TYPE=${EBS_VOLUME_TYPE:-gp2}
VOLUME_IOPS=${EBS_VOLUME_IOPS}
MONGO_DIR=${MONGO_DIR:-/ebs/mongo}

# TODO: support volume resizing,
#       migrating between AZ,
#       duplicate vs detach, etc

if [[ "$VOLUME_NAME" != "" ]]; then
  devices=$(mongo-free-devices)
  VOLUME_DEVICE=$(echo "$devices" | head -n 1)

  if [[ "$VOLUME_DEVICE" == "" ]]; then
    echo "Not enough available devices!"
    exit 1
  fi

  VOLUME_OPTS="--volume-type $VOLUME_TYPE"
  if [[ "$VOLUME_IOPS" != "" ]]; then
    VOLUME_OPTS="$VOLUME_OPTS --iops $VOLUME_IOPS"
  fi

  mongo-add-volume $VOLUME_NAME $VOLUME_SIZE $VOLUME_DEVICE $VOLUME_OPTS

  DEVICE=$(mongo-volume-device $VOLUME_NAME)

  mkfs.xfs $DEVICE 2>/dev/null
  mkdir -p $MONGO_DIR 2>/dev/null
  umount $MONGO_DIR 2>/dev/null
  mount -t xfs -o noatime,nodiratime,noexec $DEVICE $MONGO_DIR 2>/dev/null
fi
