#! /bin/bash

# Creates an EBS snapshot of mongo database. Locks mongo and
# freezes the filesystem before snapshotting

MONGO_DIR=${MONGO_DIR:?"MONGO_DIR must be set"}
MONGO_USER=${MONGO_USER:?"MONGO_USER must be set"}
MONGO_PASSWORD=${MONGO_PASSWORD:?"MONGO_PASSWORD must be set"}
MONGO_HOST=${MONGO_HOST:?"MONGO_HOST must be set"}
MONGO_PORT=${MONGO_PORT:-27017}
BACKUP_NAME=${BACKUP_NAME:?"BACKUP_NAME must be set"}
BACKUP_MAX_DAYS=${BACKUP_MAX_DAYS:-7}
BACKUP_MIN_COUNT=${BACKUP_MIN_COUNT:-3}

REGION=$(wget -qO- http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
AZ=$(wget -qO- http://169.254.169.254/latest/meta-data/placement/availability-zone)
ID=$(wget -qO- http://169.254.169.254/latest/meta-data/instance-id)

if [[ ! -e /var/run/convoy ]]; then
  echo "backup only enabled when convoy is available"
  sleep 30
  exit 1
fi

primary=$(mongo $MONGO_HOST/admin --eval "rs.isMaster().primary" | tail -n +3)
if [[ "$primary" == "$MONGO_HOST:$MONGO_PORT" ]]; then
  echo "refusing to backup primary instance."
  sleep 30
  exit 1
fi

DEVICE=$(mount | grep $MONGO_DIR | awk '{ print $1 }')
VOLUME_ID=$(aws ec2 describe-volumes --region $REGION | jq -r '.Volumes[] | .Attachments[] | select(.Device == "'$DEVICE'" and .InstanceId == "'$ID'") | .VolumeId')

if [[ "$VOLUME_ID" == "" ]]; then
  echo "Cannot identify volume id to backup"
  sleep 30
  exit 1
fi

## Lock database
mongo ${MONGO_HOST}:${MONGO_PORT}/admin -u ${MONGO_USER} -p${MONGO_PASSWORD} --eval 'db.fsyncLock()'
fsfreeze -f ${MONGO_DIR}

## Create snapshots
SNAPSHOT_ID=$(aws ec2 create-snapshot --region $REGION --volume-id $VOLUME_ID | jq -r .SnapshotId)

## Unlock database
fsfreeze -u ${MONGO_DIR}
mongo ${MONGO_HOST}:${MONGO_PORT}/admin -u ${MONGO_USER} -p${MONGO_PASSWORD} --eval "db.fsyncUnlock()"

## Wait for snapshot to complete
SNAPSHOT_STATE=$(aws ec2 describe-snapshots --region $REGION --snapshot-id $SNAPSHOT_ID | jq -r '.Snapshots[] | .State')

while [[ "$SNAPSHOT_STATE" != "completed" ]]; then
  sleep 10
  echo "waiting for snapshot $SNAPSHOT_ID to complete..."
  SNAPSHOT_STATE=$(aws ec2 describe-snapshots --region $REGION --snapshot-id $SNAPSHOT_ID | jq -r '.Snapshots[] | .State')
done

echo "Tagging snapshot"
aws ec2 create-tags --region $REGION --resources $SNAPSHOT_ID --tags "Key=Name,Value=$BACKUP_NAME"
